version: "3.8"
services:
  backend:
    restart: always
    image: node
    depends_on:
      - mongo
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
    ports:
      - 3000:3000
    networks:
      - mynet
    command: sh -c 'npm install && npm install -g nodemon && npm run start:dev'

  frontend:
    restart: always
    image: node
    volumes:
      - ./frontend/:/app
    ports:
      - 8080:8080
    networks:
      - mynet
    command: sh -c 'npm install && npm install -g @vue/cli && npm run serve'

  mongo:
    image: mongo:6-jammy
    environment:
      - MONGODB_DATABASE="overcode"
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - 8081:8081

networks:
  mynet:
    driver: bridge

volumes:
  dbdata6:
